package com.greathiit.ytyy.mapper;

import com.greathiit.ytyy.entity.Reservationtime;
import java.util.List;

public interface ReservationtimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int deleteByPrimaryKey(String restimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int insert(Reservationtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    Reservationtime selectByPrimaryKey(String restimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    List<Reservationtime> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int updateByPrimaryKey(Reservationtime record);
}