package com.greathiit.ytyy.mapper;

import com.greathiit.ytyy.entity.Reservationstu;
import java.util.List;

public interface ReservationstuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION_STU
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int deleteByPrimaryKey(String resstuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION_STU
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int insert(Reservationstu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION_STU
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    Reservationstu selectByPrimaryKey(String resstuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION_STU
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    List<Reservationstu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESERVATION_STU
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int updateByPrimaryKey(Reservationstu record);
}