package com.greathiit.ytyy.mapper;

import com.greathiit.ytyy.entity.Usrusrtudent;
import java.util.List;

public interface UsrusrtudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR_USRSTUDENT
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int deleteByPrimaryKey(Integer usId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR_USRSTUDENT
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int insert(Usrusrtudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR_USRSTUDENT
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    Usrusrtudent selectByPrimaryKey(Integer usId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR_USRSTUDENT
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    List<Usrusrtudent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR_USRSTUDENT
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int updateByPrimaryKey(Usrusrtudent record);
}