package com.greathiit.ytyy.mapper;

import com.greathiit.ytyy.entity.Usrusuradmin;
import java.util.List;

public interface UsrusuradminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR_USURADMIN
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int deleteByPrimaryKey(String uaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR_USURADMIN
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int insert(Usrusuradmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR_USURADMIN
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    Usrusuradmin selectByPrimaryKey(String uaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR_USURADMIN
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    List<Usrusuradmin> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR_USURADMIN
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int updateByPrimaryKey(Usrusuradmin record);
}