package com.greathiit.ytyy.mapper;

import com.greathiit.ytyy.entity.Venueinfo;
import java.util.List;

public interface VenueinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VENUE_INFO
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int deleteByPrimaryKey(Integer vinfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VENUE_INFO
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int insert(Venueinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VENUE_INFO
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    Venueinfo selectByPrimaryKey(Integer vinfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VENUE_INFO
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    List<Venueinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VENUE_INFO
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int updateByPrimaryKey(Venueinfo record);
}