package com.greathiit.ytyy.mapper;

import com.greathiit.ytyy.entity.Venuetime;
import java.util.List;

public interface VenuetimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VENUE_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int deleteByPrimaryKey(Integer vtimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VENUE_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int insert(Venuetime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VENUE_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    Venuetime selectByPrimaryKey(Integer vtimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VENUE_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    List<Venuetime> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VENUE_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    int updateByPrimaryKey(Venuetime record);
}