package com.greathiit.ytyy.entity;

public class Reservationstu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESERVATION_STU.RESSTU_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private String resstuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESERVATION_STU.US_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private Integer usId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESERVATION_STU.VINFO_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private String vinfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESERVATION_STU.RESSTU_ID
     *
     * @return the value of RESERVATION_STU.RESSTU_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public String getResstuId() {
        return resstuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESERVATION_STU.RESSTU_ID
     *
     * @param resstuId the value for RESERVATION_STU.RESSTU_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setResstuId(String resstuId) {
        this.resstuId = resstuId == null ? null : resstuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESERVATION_STU.US_ID
     *
     * @return the value of RESERVATION_STU.US_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public Integer getUsId() {
        return usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESERVATION_STU.US_ID
     *
     * @param usId the value for RESERVATION_STU.US_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setUsId(Integer usId) {
        this.usId = usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESERVATION_STU.VINFO_ID
     *
     * @return the value of RESERVATION_STU.VINFO_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public String getVinfoId() {
        return vinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESERVATION_STU.VINFO_ID
     *
     * @param vinfoId the value for RESERVATION_STU.VINFO_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setVinfoId(String vinfoId) {
        this.vinfoId = vinfoId == null ? null : vinfoId.trim();
    }
}