package com.greathiit.ytyy.entity;

import java.util.Date;

public class Reservationtime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESERVATION_TIME.RESTIME_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private String restimeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESERVATION_TIME.RES_IN_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private Date resInTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESERVATION_TIME.RES_OUT_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private Date resOutTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESERVATION_TIME.RESTIME_ID
     *
     * @return the value of RESERVATION_TIME.RESTIME_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public String getRestimeId() {
        return restimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESERVATION_TIME.RESTIME_ID
     *
     * @param restimeId the value for RESERVATION_TIME.RESTIME_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setRestimeId(String restimeId) {
        this.restimeId = restimeId == null ? null : restimeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESERVATION_TIME.RES_IN_TIME
     *
     * @return the value of RESERVATION_TIME.RES_IN_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public Date getResInTime() {
        return resInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESERVATION_TIME.RES_IN_TIME
     *
     * @param resInTime the value for RESERVATION_TIME.RES_IN_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setResInTime(Date resInTime) {
        this.resInTime = resInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESERVATION_TIME.RES_OUT_TIME
     *
     * @return the value of RESERVATION_TIME.RES_OUT_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public Date getResOutTime() {
        return resOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESERVATION_TIME.RES_OUT_TIME
     *
     * @param resOutTime the value for RESERVATION_TIME.RES_OUT_TIME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setResOutTime(Date resOutTime) {
        this.resOutTime = resOutTime;
    }
}