package com.greathiit.ytyy.entity;

public class Usrcollege {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR_COLLEGE.US_COLLEGE_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private Integer usCollegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR_COLLEGE.US_COLLEGE_NAME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private String usCollegeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_COLLEGE.US_COLLEGE_ID
     *
     * @return the value of USR_COLLEGE.US_COLLEGE_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public Integer getUsCollegeId() {
        return usCollegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_COLLEGE.US_COLLEGE_ID
     *
     * @param usCollegeId the value for USR_COLLEGE.US_COLLEGE_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setUsCollegeId(Integer usCollegeId) {
        this.usCollegeId = usCollegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_COLLEGE.US_COLLEGE_NAME
     *
     * @return the value of USR_COLLEGE.US_COLLEGE_NAME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public String getUsCollegeName() {
        return usCollegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_COLLEGE.US_COLLEGE_NAME
     *
     * @param usCollegeName the value for USR_COLLEGE.US_COLLEGE_NAME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setUsCollegeName(String usCollegeName) {
        this.usCollegeName = usCollegeName == null ? null : usCollegeName.trim();
    }
}