package com.greathiit.ytyy.entity;

public class Usrusrtudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR_USRSTUDENT.US_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private Integer usId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR_USRSTUDENT.US_COLLEGE
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private String usCollege;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR_USRSTUDENT.US_NO
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private String usNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR_USRSTUDENT.US_NAME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private String usName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR_USRSTUDENT.STSTU_TYPE
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private String ststuType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_USRSTUDENT.US_ID
     *
     * @return the value of USR_USRSTUDENT.US_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public Integer getUsId() {
        return usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_USRSTUDENT.US_ID
     *
     * @param usId the value for USR_USRSTUDENT.US_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setUsId(Integer usId) {
        this.usId = usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_USRSTUDENT.US_COLLEGE
     *
     * @return the value of USR_USRSTUDENT.US_COLLEGE
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public String getUsCollege() {
        return usCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_USRSTUDENT.US_COLLEGE
     *
     * @param usCollege the value for USR_USRSTUDENT.US_COLLEGE
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setUsCollege(String usCollege) {
        this.usCollege = usCollege == null ? null : usCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_USRSTUDENT.US_NO
     *
     * @return the value of USR_USRSTUDENT.US_NO
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public String getUsNo() {
        return usNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_USRSTUDENT.US_NO
     *
     * @param usNo the value for USR_USRSTUDENT.US_NO
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setUsNo(String usNo) {
        this.usNo = usNo == null ? null : usNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_USRSTUDENT.US_NAME
     *
     * @return the value of USR_USRSTUDENT.US_NAME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public String getUsName() {
        return usName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_USRSTUDENT.US_NAME
     *
     * @param usName the value for USR_USRSTUDENT.US_NAME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setUsName(String usName) {
        this.usName = usName == null ? null : usName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_USRSTUDENT.STSTU_TYPE
     *
     * @return the value of USR_USRSTUDENT.STSTU_TYPE
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public String getStstuType() {
        return ststuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_USRSTUDENT.STSTU_TYPE
     *
     * @param ststuType the value for USR_USRSTUDENT.STSTU_TYPE
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setStstuType(String ststuType) {
        this.ststuType = ststuType == null ? null : ststuType.trim();
    }
}