package com.greathiit.ytyy.entity;

public class Usrusuradmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR_USURADMIN.UA_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private String uaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR_USURADMIN.UA_NAME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private String uaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR_USURADMIN.UA_PASSWORD
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private String uaPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_USURADMIN.UA_ID
     *
     * @return the value of USR_USURADMIN.UA_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public String getUaId() {
        return uaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_USURADMIN.UA_ID
     *
     * @param uaId the value for USR_USURADMIN.UA_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setUaId(String uaId) {
        this.uaId = uaId == null ? null : uaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_USURADMIN.UA_NAME
     *
     * @return the value of USR_USURADMIN.UA_NAME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public String getUaName() {
        return uaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_USURADMIN.UA_NAME
     *
     * @param uaName the value for USR_USURADMIN.UA_NAME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setUaName(String uaName) {
        this.uaName = uaName == null ? null : uaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_USURADMIN.UA_PASSWORD
     *
     * @return the value of USR_USURADMIN.UA_PASSWORD
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public String getUaPassword() {
        return uaPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_USURADMIN.UA_PASSWORD
     *
     * @param uaPassword the value for USR_USURADMIN.UA_PASSWORD
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setUaPassword(String uaPassword) {
        this.uaPassword = uaPassword == null ? null : uaPassword.trim();
    }
}