package com.greathiit.ytyy.entity;

public class Venueinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VENUE_INFO.VINFO_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private Integer vinfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VENUE_INFO.VINFO_NAME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private String vinfoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VENUE_INFO.VINFO_MAX_NUM
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private Integer vinfoMaxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VENUE_INFO.VTIME_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    private String vtimeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VENUE_INFO.VINFO_ID
     *
     * @return the value of VENUE_INFO.VINFO_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public Integer getVinfoId() {
        return vinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VENUE_INFO.VINFO_ID
     *
     * @param vinfoId the value for VENUE_INFO.VINFO_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setVinfoId(Integer vinfoId) {
        this.vinfoId = vinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VENUE_INFO.VINFO_NAME
     *
     * @return the value of VENUE_INFO.VINFO_NAME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public String getVinfoName() {
        return vinfoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VENUE_INFO.VINFO_NAME
     *
     * @param vinfoName the value for VENUE_INFO.VINFO_NAME
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setVinfoName(String vinfoName) {
        this.vinfoName = vinfoName == null ? null : vinfoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VENUE_INFO.VINFO_MAX_NUM
     *
     * @return the value of VENUE_INFO.VINFO_MAX_NUM
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public Integer getVinfoMaxNum() {
        return vinfoMaxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VENUE_INFO.VINFO_MAX_NUM
     *
     * @param vinfoMaxNum the value for VENUE_INFO.VINFO_MAX_NUM
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setVinfoMaxNum(Integer vinfoMaxNum) {
        this.vinfoMaxNum = vinfoMaxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VENUE_INFO.VTIME_ID
     *
     * @return the value of VENUE_INFO.VTIME_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public String getVtimeId() {
        return vtimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VENUE_INFO.VTIME_ID
     *
     * @param vtimeId the value for VENUE_INFO.VTIME_ID
     *
     * @mbg.generated Fri Sep 25 13:21:03 CST 2020
     */
    public void setVtimeId(String vtimeId) {
        this.vtimeId = vtimeId == null ? null : vtimeId.trim();
    }
}